process.env.NODE_ENV = "test";
process.env.DATABASE_URL = "postgresql://user:password@localhost:5432/auth_db";
process.env.JWT_ACCESS_SECRET = "test-access-secret-long";
process.env.JWT_REFRESH_SECRET = "test-refresh-secret-long";
process.env.JWT_ISSUER = "https://auth.temis.co.kr";
process.env.JWT_AUDIENCE = "temis";
process.env.FRONTEND_REDIRECT_URL = "http://localhost:3000/auth/callback";
process.env.GOOGLE_CLIENT_ID = "google";
process.env.GOOGLE_CLIENT_SECRET = "google-secret";
process.env.GOOGLE_REDIRECT_URI = "http://localhost:4000/auth/google/callback";
process.env.NAVER_CLIENT_ID = "naver";
process.env.NAVER_CLIENT_SECRET = "naver-secret";
process.env.NAVER_REDIRECT_URI = "http://localhost:4000/auth/naver/callback";
process.env.KAKAO_CLIENT_ID = "kakao";
process.env.KAKAO_CLIENT_SECRET = "kakao-secret";
process.env.KAKAO_REDIRECT_URI = "http://localhost:4000/auth/kakao/callback";
process.env.MAIL_PROVIDER = "dev";
delete process.env.SMTP_HOST;
delete process.env.SMTP_USERNAME;
delete process.env.SMTP_PASSWORD;
